spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/Users/smile/Desktop/ToolApi/db/tool_api
    username: root
    password: 8765551730
  h2:
    console:
      path: /h2-console
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  port: 10521
wx:
  appId: wx53df3e44b7ec396d
  secret: 93546c0ea60846721a6e6ff86f28b86b
logging:
  file:
    name: toolApi.log


