spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wx_program
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

server:
  port: 10521

wx:
  appId: wx74559f2e91870c33
  secret: c2ae076b585bd3962998efd99e5b1a6d

logging:
  file:
    name: toolApi.log
    path: G:\Github\ToolApi\logs

